USE `university_bookstore`;
Drop TABLE rent;
Drop TABLE buy;
Drop TABLE standard_books;
Drop TABLE customized_books;
Drop TABLE textbooks;
Drop TABLE courses;
Drop TABLE semesters;
DROP TRIGGER IF EXISTS `removespace`;
Drop TABLE students;
Drop TABLE university;
Drop TABLE bookstores;
Drop DATABASE university_bookstore;